# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: test
    jobs:
    - job: job
      steps:
      - task: Go@0
        inputs:
          command: 'build'
          workingDirectory: '$(System.DefaultWorkingDirectory)'