apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "prolog.fullname" }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ include "prolog.fullname"}}
  serviceName: {{ include "prolog.fullname"}}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: myapp
    spec:
      initContainers:
        - name: {{ include "prolog.fullname"}}-config-init
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            -
      containers:
        - name: {{ include "prolog.fullname"}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.rpcPort}}
              name: rpc
            - containerPort: {{ .Values.serfPort}}
              name: serf
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage }}
