kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /Users/bannnnn./Documents/Documents - Bannnnn’s MacBook Air/Learn/go/proglog/data
        containerPath: /var/run/prolog