kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
  - |
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: ClusterConfiguration
    networking:
      dnsDomain: "cluster.local"
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /Users/bannnnn./Documents/Documents - Bannnnn’s MacBook Air/Learn/go/proglog/data
        containerPath: /var/run/prolog